#!/usr/bin/env python

from urlparse import urlparse
from urllib2 import urlopen
import argparse
import os
import pakrat
import shutil
import sys
import time
import yaml

class RepoCallback(object):
    def repo_init(self, repo_id, num_pkgs):
        print('Found %d packages in repo %s' % (num_pkgs, repo_id))
    def repo_metadata(self, repo_id, status):
        print('Metadata for repo %s is now %s' % (repo_id, status))

def log(msg, plain=False):
    if plain == True:
        print(msg)
    else:
        print("==> [{0}] {1}".format(time.strftime('%Y-%m-%d %X %Z'), msg))

# make directories only if they don't exist
def safe_makedirs(path, mode = None):
    if not os.path.exists(path):
        if mode != None:
            os.makedirs(path, mode)
        else:
            os.makedirs(path)

# load configuration
def repo_config():
    with open(REPOFILE) as f:
        config = yaml.safe_load(f)
        if type(config) != dict:
            log('Malformed configuration file')
            sys.exit(1)
        else:
            return config

# return a friendly name without '/'s
def friendly(name):
    return sanitize(name).replace('/', '-')

def sanitize(name):
    return name.strip().strip('/')

# create folders needed for syncing
def setup_folders(repos):
    # setup public folder
    public = os.path.join(OUTDIR, 'public')
    safe_makedirs(public)

    # directories for repos
    for repo in repos:
        real_path = os.path.join(OUTDIR, friendly(repo))
        symbolic_path = os.path.join(public, sanitize(repo))
        safe_makedirs(real_path)
        head, tail = os.path.split(symbolic_path)
        safe_makedirs(head)
        os.chdir(head)
        relative_path = os.path.relpath(real_path)
        # clean out symbolic_path if incorrect
        if os.path.islink(symbolic_path):
            if os.readlink(symbolic_path) != relative_path:
                os.unlink(symbolic_path)
        elif os.path.isdir(symbolic_path):
            shutil.rmtree(symbolic_path)
        elif os.path.isfile(symbolic_path):
            os.unlink(symbolic_path)
        # setup symbolic link if missing
        if not os.path.exists(symbolic_path):
            os.symlink(relative_path, symbolic_path)

def download_gpg(config):
    for repo, opts in config.iteritems():
        real_path = os.path.join(OUTDIR, friendly(repo))
        if opts.has_key('gpgkey'):
            try:
                key_name = os.path.basename(urlparse(opts['gpgkey']).path)
                key_data = urlopen(opts['gpgkey'])
                with open(os.path.join(real_path, key_name), 'w') as f:
                    f.write(key_data.read())
                key_data.close()
            except:
                log('Unable to download %s' % opts['gpgkey'], plain=True)
                pass

def sync_repos(config):
    version = time.strftime('%Y-%m-%d')
    repo_factories = []

    for repo, opts in config.iteritems():
        r = None
        if 'baseurls' in opts:
            r = pakrat.repo.factory(
                friendly(repo),
                baseurls=opts['baseurls']
            )
        elif 'mirrorlist' in opts:
            r = pakrat.repo.factory(
                friendly(repo),
                mirrorlist=opts['mirrorlist']
            )
        if r != None:
            repo_factories.append(r)

    repos, errors, elapsed = pakrat.sync(
        basedir=OUTDIR,
        objrepos=repo_factories,
        repoversion=version,
        callback=RepoCallback()
    )

    return repos, errors, elapsed

def main():
    log('parsing configuration')
    config = repo_config()
    for repo in config.iterkeys():
        log(repo, plain=True)
    setup_folders(config.keys())
    download_gpg(config)
    log('syncing repositories')
    repos, errors, elapsed = sync_repos(config)
    repo_str = 'repository' if repos == 1 else 'repositories'
    error_str = 'error' if errors == 1 else 'errors'
    log('%d %s, %d %s, %s' % (repos, repo_str, errors, error_str, elapsed))

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('-o', '--outdir', action='store', required=True)
    parser.add_argument('-c', '--config', action='store', required=True)
    args = parser.parse_args()
    REPOFILE = args.config
    OUTDIR = args.outdir
    main()
